# Generated by Django 3.0.8 on 2020-07-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_name', models.CharField(max_length=50)),
                ('depart_image', models.CharField(max_length=100)),
                ('depart_loc', models.CharField(max_length=100)),
                ('total_project', models.IntegerField(default=0)),
                ('tax_income', models.IntegerField(default=0)),
                ('tax_outcome', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('period_date', models.CharField(max_length=50)),
                ('project_depart', models.CharField(max_length=50)),
                ('project_url', models.CharField(max_length=100)),
            ],
        ),
    ]
