# Generated by Django 3.0.8 on 2020-07-23 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BizViz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 17, 52, 3, 530091)),
        ),
    ]
