# Generated by Django 3.0.8 on 2020-07-23 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BizViz', '0002_support_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='project_url',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='support',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 17, 57, 3, 306488)),
        ),
    ]
