# Generated by Django 3.0.8 on 2020-07-24 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BizViz', '0003_auto_20200723_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='project_hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='support',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 11, 15, 45, 989217)),
        ),
    ]
