# Generated by Django 3.0.8 on 2020-08-03 02:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BizViz', '0004_auto_20200724_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='id',
        ),
        migrations.AddField(
            model_name='department',
            name='depart_desc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='department',
            name='depart_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='support',
            name='project_depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BizViz.Department'),
        ),
        migrations.AlterField(
            model_name='support',
            name='project_url',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='support',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 11, 36, 32, 989417)),
        ),
    ]
